### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by sumitrk** [cupofdata/www-site#62] opened 2018-02-09 19:35 UTC
<img width="345" alt="https___cod-www_netlify_com_" src="https://user-images.githubusercontent.com/9337878/36046314-7a829644-0dfe-11e8-814e-951f5e08f628.png">

**Comment by jgwerner** [comment] 2018-02-11 00:59
Closing, duplicate of #19

**Closed by jgwerner** 2018-02-11 00:59 UTC
